### ISSUE TITLE
Logitech-LED SDK could not initialize

### ISSUE THREAD

**Issue by GabeHirakawa** [antonpup/Logitech-CSGO#10]
I'm getting this error on launch of the .exe. I was trying to find the code for the error message but couldn't. Help with this would be appreciated :)! I really am liking what you're doing with this, it's really cool. I have some ideas and will hopefully make a pull request in the near feature.

Thanks,

Gabriel 'stealth_^' Hirakawa

**Comment by antonpup** [comment]
I suspect it has something to do with 32-bit and 64-bit machines. After I'm done with my Dota 2 integration, I will update this with logging and a 32-bit download. Feel free to make a PR, although I have quite a bit changed on my local.

**Comment by GabeHirakawa** [comment]
Weird, I have a 64-Bit system as well.

**Comment by GabeHirakawa** [comment]
After a little testing, I found that it is an Issue with the LogitechLEDEnginesWrapper.

Continuing testing. Standby

**Comment by GabeHirakawa** [comment]
Andddd I figured it out. For whatever reason the newest LGS is completely broken with this sort of thing.

I used this URL to download 8.58 and everything works flawlessly now...Weird.

http://download01.logitech.com/web/ftp/pub/techsupport/gaming/LGS_8.58.183_x64_Logitech.exe

EDIT: Doesn't detect my G633s. Errr.

EDIT2: Seems to be a problem with 8.78. After updating 8.79 I no longer have issues.

Case Closed (Guess I should've done this before I made an issue report)

**Comment by Ge0rges** [comment]
Hello all. I'm getting this again with latest version of both aurora and G Hub. At first launch it worked, and then when it stopped working I selected "Override DLL" and it worked again, but after closing it now no longer works.

**Comment by antonpup** [comment]
If you read the readme on this project, it's been replaced by Aurora and is no longer being developed. I would make an issue on [Aurora's github](https://github.com/antonpup/Aurora). Maybe someone who maintains Aurora would be able to help you.
