### ISSUE TITLE
Request: German Keyboard Layout or more flexible customization

### ISSUE THREAD

**Issue by stevenobird** [antonpup/Logitech-CSGO#13]
Since I use a german G910 Orion Spark, two of my keys are not illuminated and cannot be set in the configurator, since they don't exist in at least the US or UK layout.

The keys are the following (VK codes taken by https://msdn.microsoft.com/en-us/library/ms892159.aspx?f=255&MSPPError=-2147217396):
OEM_102 (consists of |, < and >)
OEM_2 (consists of # and ')

So it would be nice to either make more layouts possible or also capture keys not only by clicking on the representing button in the virtual keyboard, but also by key-pressure.

**Comment by antonpup** [comment]
I actually already did German, UK, French, International, and Russian layouts in another program that I am developing. I have moved onto combining my CSGO and Dota 2 implementations into one, with more features. Add me on steam, I will add you to the testing team for Aurora. [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/)
