### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Benyy** [antonpup/Logitech-CSGO#16]
I am experiencing some major lag on health, ammo and typing. The bomb flashing on numpad works fine but the ammo, health is responding really slow or won't even work. Can you help me please?

**Comment by antonpup** [comment]
That is s known issue across GSI. I've reported the issue to Valve, there's nothing I can do about it.

**Comment by Benyy** [comment]
ok thank you

**Comment by RobertBeekman** [comment]
Did you ever hear back from Valve on this? I tweeted them but got nothing back.
The NodeJS example they have on the Wiki has the same issue but Logitech's support for CS:GO does not

**Comment by antonpup** [comment]
No. I've been too busy developing Aurora for other games. I will shoot them an email again this week. Will definitely try to get it sorted before the release.

**Comment by RobertBeekman** [comment]
Ah ok I see. What's Aurora about? :)
