### ISSUE TITLE
Logitech-LED SDK could not initialize

### ISSUE THREAD

**Issue by lefkas** [antonpup/Logitech-CSGO#17]
So i get this errormsg, 
Tried this "solution":
https://github.com/antonpup/Logitech-CSGO/issues/10 (downgrading LGS) had latest v8.81
Also tried this "solution":
https://github.com/antonpup/Logitech-CSGO/issues/11
(downgrading Visual C++ Redistributable for Visual Studio to 2012 Update 4 )
Still wont work.
![capture](https://cloud.githubusercontent.com/assets/19966059/16303888/4a4ed48c-3953-11e6-9354-7ad57b06baa5.JPG)
First i was looking for how to make ARX show stats from when i play csgo and found your work on youtube, wich looks cool...)
Thank - Jens

**Comment by antonpup** [comment]
This project was replaced by a better one. Please take a look at Aurora, https://github.com/antonpup/Aurora

Thank you.

**Comment by lefkas** [comment]
Thanks for the fast reply man, installed it and looked at it a little, will try it asap.
You dont happen to know what to search for to get stats from csgo to show on the mobile with Logitech G910?
Thanks!
