### ISSUE TITLE
Keyboard languages/layouts

### ISSUE THREAD

**Issue by HeartBeatx** [antonpup/Logitech-CSGO#2]
Are you able to enable other languages/layouts?
On the Danish version of the keyboard, the \* ' and the < > \ do not light up
I have also seen this happen with other programs like the g910 keyboard spectrogram (2.2.0) and the demos that come with the SDK

**Comment by Razor2143** [comment]
Same thing happens on DE layout for left shift, < >, # '.
Somehow left shift doesn't light up at all and the other ones stay in the usual colour.

**Comment by arjanvanschendel** [comment]
Same here, left shift and the |-key aren't lighting up. Also, the g-keys keep their original color.

**Comment by antonpup** [comment]
I can see what I can do about the non-lit keys. The g-keys and logos are not affected by this tool because the LEDSDK doesn't allow for individual changes to those.

Get in touch with me on Steam, link's in the About tab. Comment on my profile first, so I know who to add.

**Comment by antonpup** [comment]
Fixed in [v0.4.0](https://github.com/antonpup/Logitech-CSGO/releases/tag/v0.4.0)
