### ISSUE TITLE
Input lag

### ISSUE THREAD

**Issue by EnricoBaivo** [antonpup/Logitech-CSGO#4]
when i start your programm the input-leg increase. so when i am typing the delay to do the action is like more then 1s. And the Logitech gaming software getting really slow .

I think the problem is the g 633, after the device is disabled the inputlags decrase. but i am sure there are still some

Windows 10 64 bit 
intel i5
gforce 790 gtx oc
g910
g303
g633

**Comment by Snoopiashigaru** [comment]
I think the problem is the g 633, after the device is disabled the inputlags decrase. but i am sure there are still some

**Comment by antonpup** [comment]
I'll look into it.

**Comment by antonpup** [comment]
Fixed in [v0.4.1](https://github.com/antonpup/Logitech-CSGO/releases/tag/v0.4.1)
