### ISSUE TITLE
Only works once after starting

### ISSUE THREAD

**Issue by Nothing4You** [antonpup/Logitech-CSGO#5]
Hey there,

I'm using Win 8.1 x64.

After having started this software game-related coloring works exactly one time.
If I close CSGO and start it again it will just keep the LGS default profile for the game.
Closing CSGO and this plugin, then restarting both gets it back for one more run.
For each consequent run I have to repeat closing this addon and starting it again before I start CSGO.

**Comment by Nothing4You** [comment]
Nevermind, it just doesn't load the default colors until entering a map.

**Comment by antonpup** [comment]
Was the issue you were having that LGS would override the colors from this program?

**Comment by Nothing4You** [comment]
Yes, it was showing the colors that are "normal" for my csgo profile.

**Comment by Nothing4You** [comment]
I'm not sure though that this program was actually setting them at all after starting csgo.before entering a match.

**Comment by antonpup** [comment]
I'll make it update at least once per second so it will override LGS. Thank you for pointing this out.

**Comment by EnricoBaivo** [comment]
i thought this is normal ?

**Comment by antonpup** [comment]
Added a refresh rate of 1 second to connected devices in [v0.4.2](https://github.com/antonpup/Logitech-CSGO/releases/tag/v0.4.2).

**Comment by Nothing4You** [comment]
Looks good, thanks!
