### ISSUE TITLE
Background Leds able to customize 

### ISSUE THREAD

**Issue by EnricoBaivo** [antonpup/Logitech-CSGO#6]
Would be awesome if the next feature would be diffrent colors in the background section. (Diffrent colors for choosen keys)

**Comment by antonpup** [comment]
So, you want to set what keys are considered as the background? Or do you want to display a custom pattern in the background instead of all lights being solid?

**Comment by EnricoBaivo** [comment]
Sorry i mean at the static options diffrent colors for diffrent keys. 

so the user can choose for exemple "w,a,s,d" should light for exempel"blue" and the keys "g,h,j,k" should light for exempel "red" .

**Comment by antonpup** [comment]
Added another static keys group in [v0.4.2](https://github.com/antonpup/Logitech-CSGO/releases/tag/v0.4.2).
