### ISSUE TITLE
LED Blinking when running

### ISSUE THREAD

**Issue by ni4321** [antonpup/Logitech-CSGO#7]
As title says, the LED's blink when the program is running. They are fine when using the Logitech software but when the integration software is booted, the LED's quickly blink for a split second every second.

**Comment by antonpup** [comment]
I cannot recreate this issue. Could you explain in greater detail how to recreate this? Also, please provide your computer specs.

Edit: Make sure that you have "Enable preview" off. This will cause the keyboard to update. When you aren't tweaking settings, it's best to disable the preview. You can also "close" the window, which will put the program into the tray and will disable the preview while still running.
