### ISSUE TITLE
logitechLedEnginesWrapper Error on Win10

### ISSUE THREAD

**Issue by Headstyler** [antonpup/Logitech-CSGO#9]
dont work on win 10 get a massage like " tehre was an error initializing Logitech LED SDK, logitechLedEnginesWrapper ddl dosnt found " but it is there dont know why they told this﻿

**Comment by GabeHirakawa** [comment]
Update to 8.79(latest version) I had the same problem, but it's fixed now.

**Comment by jootrnt** [comment]
I'm getting the same error with version 8.79.77. 
EDIT: I fixed this installing Visual C++ Redistributable for Visual Studio 2012 Update 4 (https://www.microsoft.com/en-us/download/details.aspx?id=30679), the 2013 was installed already but the program just started with the 2012 version

**Comment by kemalicecek** [comment]
i have same issue, but i cant fix it, LGS is newest version and I installed to Visual C++ Redistributable for Visual Studio 2012 Update 4. It has Dota2 version. Its okay, but on csgo there is a problem. help me please..

**Comment by antonpup** [comment]
@eicecek You will have to wait a bit until I release Project-Aurora. It will include both CSGO and Dota 2 lighting, with more visual effects and support for more games.

**Comment by jootrnt** [comment]
I have the Visual C++ Redistributable 2012 and 2013 installed, both x86 and x64 version, I you could try to check.

**Comment by kemalicecek** [comment]
I've got the all versions without x86 but now, the Logitech-Dota2 has same issues too :(

**Comment by kemalicecek** [comment]
@antonpup I am not a patient person, if somebody can run it, it must be could run on my pc immediately. :) I solve the Logitech-Dota2 ptoblem, but on CS-GO it says "Logitech SDK could not be initialized" :(

**Comment by antonpup** [comment]
@eicecek Contact me on Steam, http://steamcommunity.com/id/pupant/ I'll include you in testing for Aurora.
